# Generated by Django 4.0.1 on 2023-04-15 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuron', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedneuralnetwork',
            name='time_update',
            field=models.DateTimeField(null=True),
        ),
    ]
