# Generated by Django 4.0.1 on 2022-01-16 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuron', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='researcher',
            field=models.BooleanField(default=False),
        ),
    ]
