# Generated by Django 4.0.1 on 2022-01-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuron', '0002_alter_customuser_researcher'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeuralNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='networks')),
            ],
            options={
                'verbose_name': 'Нейронная сеть',
                'verbose_name_plural': 'Нейронные сети',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='researcher',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
