# Generated by Django 4.0.1 on 2023-04-20 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neuron', '0002_trainedneuralnetwork_time_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainedneuralnetworkuser',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='neuron.listсompanies'),
            preserve_default=False,
        ),
    ]
