# Generated by Django 4.0.1 on 2023-04-23 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neuron', '0003_alter_trainedneuralnetworkuser_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainedneuralnetwork',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_list_companies_for_default', to='neuron.listсompanies'),
        ),
        migrations.AlterField(
            model_name='trainedneuralnetworkuser',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_list_companies', to='neuron.listсompanies'),
        ),
    ]
