# Generated by Django 4.0.1 on 2022-03-28 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neuron', '0003_neuralnetwork_alter_customuser_researcher'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainedNeuralNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=100)),
                ('loss', models.CharField(max_length=50)),
                ('optimizer', models.CharField(max_length=50)),
                ('epochs', models.IntegerField()),
                ('batch_size', models.IntegerField()),
                ('file_trained_nn', models.FileField(upload_to='save_model_nn/%Y/%m/%d/')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('neural_network_architecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neuron.neuralnetwork')),
            ],
            options={
                'verbose_name': 'Обученная нейронная сеть',
                'verbose_name_plural': 'Обученные нейронные сети',
                'ordering': ['-time_create'],
            },
        ),
    ]
