# Generated by Django 4.0.1 on 2022-04-02 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuron', '0004_trainedneuralnetwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListСompanies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ticker', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'ordering': ['id'],
            },
        ),
    ]
