# Generated by Django 4.0.1 on 2023-04-23 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neuron', '0004_alter_trainedneuralnetwork_company_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NeuralNetwork',
            new_name='ArchitectureNeuralNetwork',
        ),
    ]
