# Generated by Django 4.0.1 on 2022-04-02 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuron', '0005_listсompanies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listсompanies',
            name='ticker',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
