# Generated by Django 4.0.1 on 2022-04-16 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuron', '0006_alter_listсompanies_ticker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listсompanies',
            options={'ordering': ['ticker'], 'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AddField(
            model_name='trainedneuralnetwork',
            name='time_step',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='listсompanies',
            name='ticker',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='trainedneuralnetwork',
            name='loss',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trainedneuralnetwork',
            name='optimizer',
            field=models.CharField(max_length=100),
        ),
    ]
