# Generated by Django 4.0.1 on 2022-04-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuron', '0007_alter_listсompanies_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainedneuralnetwork',
            name='loss',
            field=models.CharField(choices=[('Probabilistic losses', (('binary_crossentropy', 'binary_crossentropy'), ('categorical_crossentropy', 'categorical_crossentropy'), ('sparse_categorical_crossentropy', 'sparse_categorical_crossentropy'), ('poisson', 'poisson'), ('kl_divergence', 'kl_divergence'))), ('Regression losses', (('mean_squared_error', 'mean_squared_error'), ('mean_absolute_error', 'mean_absolute_error'), ('mean_absolute_percentage_error', 'mean_absolute_percentage_error'), ('mean_squared_logarithmic_error', 'mean_squared_logarithmic_error'), ('cosine_similarity', 'cosine_similarity'), ('huber_loss', 'huber_loss'), ('log_cosh', 'log_cosh'))), ('Hinge losses for "maximum-margin" classification', (('hinge', 'hinge'), ('squared_hinge', 'squared_hinge'), ('categorical_hinge', 'categorical_hinge')))], max_length=100),
        ),
        migrations.AlterField(
            model_name='trainedneuralnetwork',
            name='optimizer',
            field=models.CharField(choices=[('SGD', 'SGD'), ('RMSprop', 'RMSprop'), ('Adam', 'Adam'), ('Adadelta', 'Adadelta'), ('Adadelta', 'Adadelta'), ('Adamax', 'Adamax'), ('Nadam', 'Nadam'), ('Ftrl', 'Ftrl')], max_length=100),
        ),
    ]
