# Generated by Django 4.0.1 on 2022-04-18 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neuron', '0008_alter_trainedneuralnetwork_loss_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainedneuralnetwork',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
