# Generated by Django 4.0.1 on 2022-04-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuron', '0009_alter_trainedneuralnetwork_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='researcher',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
