# Generated by Django 4.0.1 on 2022-04-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuron', '0010_customuser_username2_alter_customuser_researcher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username2',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='researcher',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
