# Generated by Django 4.0.1 on 2022-04-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuron', '0011_remove_customuser_username2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainedneuralnetwork',
            name='creator',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
